### ISSUE TITLE
Missing property in AttachVirtualDiskFlags enumeration

### ISSUE THREAD

**Issue by FaustoNascimento** [thebecwar/VirtualDiskInterop#3]
According to the headers, there's a missing property at the end of the enum  AttachVirtualDiskFlags. It's declared as below:

// Do not assign a custom security descriptor to the disk; use the
// system default.
ATTACH_VIRTUAL_DISK_FLAG_NO_SECURITY_DESCRIPTOR         = 0x00000010,

**Comment by FaustoNascimento** [comment]
Fixed in my pull request.

**Comment by thebecwar** [comment]
Closed with a23c09879a382c8bc48fd7468ff2a09823f47136
